### ISSUE TITLE
Version numbers should be checked between tool components

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/fletch#209]
Most components of the toolschain expect the other components of the toolchain to have the same version. When that is not the case things fall apart mostly with no error message or a somewhat unrelated error message.

Related bugs:

 - [x] #157: Version number support in snapshots 
 - [x] #206: Fletch client and persistent process should agree on version number
 - [x] #208: The persistent process should check the version of the fletch-vm the fletch-agent is using
 - [x] #210: Compiler and VM should agree on version

**Comment by wibling** [comment]
Should all be fixed with the last commit 7c954a93ce6d1e52b0226d1aaabe520452798765.
